"""Training infrastructure modules."""

from .loss_functions import (
    huber_quantile_loss,
    spike_rate_distribution_loss,
    sparse_categorical_crossentropy,
    weighted_crossentropy,
    binary_crossentropy,
    mean_squared_error,
    cosine_similarity_loss,
)
from .regularizers import (
    voltage_regularization,
    voltage_regularization_v2,
    stiff_regularization,
    l2_regularization,
    l1_regularization,
    SpikeRateDistributionRegularizer,
    SpikeVoltageRegularizer,
    activity_regularization,
)
from .trainer import (
    TrainState,
    TrainMetrics,
    TrainConfig,
    V1Trainer,
    MetricsAccumulator,
    create_train_step_fn,
    create_eval_step_fn,
    create_checkpointed_forward_fn,
    create_lr_schedule,
)
from .distributed import (
    DistributedConfig,
    ShardedTrainer,
    PmapTrainer,
    create_distributed_trainer,
    get_devices,
    get_device_count,
    get_local_device_count,
    shard_batch_for_pmap,
    unshard_batch_from_pmap,
    sync_gradients,
    sync_batch_stats,
    initialize_multi_host,
    is_main_process,
    get_process_count,
    get_process_index,
)

__all__ = [
    # Loss functions
    "huber_quantile_loss",
    "spike_rate_distribution_loss",
    "sparse_categorical_crossentropy",
    "weighted_crossentropy",
    "binary_crossentropy",
    "mean_squared_error",
    "cosine_similarity_loss",
    # Regularizers
    "voltage_regularization",
    "voltage_regularization_v2",
    "stiff_regularization",
    "l2_regularization",
    "l1_regularization",
    "SpikeRateDistributionRegularizer",
    "SpikeVoltageRegularizer",
    "activity_regularization",
    # Trainer
    "TrainState",
    "TrainMetrics",
    "TrainConfig",
    "V1Trainer",
    "MetricsAccumulator",
    "create_train_step_fn",
    "create_eval_step_fn",
    "create_checkpointed_forward_fn",
    "create_lr_schedule",
    # Distributed
    "DistributedConfig",
    "ShardedTrainer",
    "PmapTrainer",
    "create_distributed_trainer",
    "get_devices",
    "get_device_count",
    "get_local_device_count",
    "shard_batch_for_pmap",
    "unshard_batch_from_pmap",
    "sync_gradients",
    "sync_batch_stats",
    "initialize_multi_host",
    "is_main_process",
    "get_process_count",
    "get_process_index",
]
